# Generated by Django 3.0.4 on 2020-03-24 02:15

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_articlecomment_category_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_summernote.fields.SummernoteTextField(null=True),
        ),
    ]
